test_word_segment:
		g++ \
            -I../include \
            -I../base \
            -I../base/cppjieba/include \
            ../src/read_documents.cpp test_read_document.cpp \
            -o test_read_document \
            -std=c++11
		g++ \
            -I../include \
            -I../base \
            -I../base/cppjieba/include \
            ../src/read_documents.cpp ../src/word_segment.cpp test_word_segment.cpp \
            -o test_word_segment \
            -std=c++11
